#---------------------------------------------------------#
#---------------RUN ANDREAS PROFILE METHODS---------------#
#---------------------------------------------------------#

# This script runs the author profile version of the impostor method.
# This version differs from the traditional version of the method as it concatenates all known works by the author.
# The impostors are also generated by concatenating a random paraphrased document of each document number for each author.
suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(idiolect)
  library(jsonlite)
})

# Function to read a JSONL file into a data frame
read_jsonl <- function(file_path) {
  lines <- readLines(file_path)
  parsed_list <- lapply(lines, function(line) {
    parsed <- fromJSON(line)
    if (is.list(parsed) && length(parsed) == 1) {
      return(parsed[[1]])
    } else {
      return(parsed)
    }
  })
  df <- do.call(rbind, lapply(parsed_list, function(x) as.data.frame(x, stringsAsFactors = FALSE)))
  return(df)
}

# This method aids in reading list columns
read_jsonl_stream <- function(file_path) {
  con <- file(file_path, open = "r", encoding = "UTF-8")
  on.exit(close(con))
  
  # stream_in reads JSON objects line-by-line
  data <- jsonlite::stream_in(con, verbose = FALSE)
  return(data)
}

# Input variables
# selected_corpus since column called corpus in metadata
base_loc <- "/Volumes/BCross/datasets/author_verification"
# base_loc <- "/Volumes/ExternalHDD/cloud_backup/datasets/author_verification"
data_type <- "training"
corpus <- "Wiki"

# Locations
data_loc <- paste0(base_loc, "/", data_type, "/", corpus)

known_loc <- paste0(data_loc, "/known_raw.jsonl")
unknown_loc <- paste0(data_loc, "/unknown_raw.jsonl")
metadata_loc <-paste0(base_loc, "/", data_type, "/metadata.rds")
impostors_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_top_impostors")
# impostors_loc <- paste0(data_loc, "/gpt_4o_mini_full/impostor_profile_top_impostors")
features_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_feature_list.rds")
# result_save_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_results_andrea_im")
result_save_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_results_andrea_lambdag")

if (!dir.exists(result_save_loc)) {
  dir.create(result_save_loc, recursive = TRUE)
}

# Get a list of all of the problems which have been completed.
# This is useful if an error occurs and you don't want to start over again.
completed_problems <- dir(result_save_loc, pattern = "\\.rds$")
completed_problems <- sub("\\.rds$", "", completed_problems)

# Read base files
# known <- readRDS(known_loc)
# unknown <- readRDS(unknown_loc)
metadata <- readRDS(metadata_loc)
# feature_list <- readRDS(features_loc)

# Filter metadata for current corpus
filtered_metadata <- metadata |> 
  filter(corpus == .env$corpus) |>
  filter(!(problem %in% completed_problems)) |>
  rownames_to_column(var = 'sample_id') 

# Get the sample_id vales
sample_ids <- filtered_metadata |> pull(sample_id) |> head(1)

# Run the impostor method across samples
for(s in sample_ids){
  
  chosen_sample <- filtered_metadata |>
    filter(sample_id == s)
  
  known_author <- chosen_sample |> pull(known_author)
  unknown_author <- chosen_sample |> pull(unknown_author)
  problem <- chosen_sample |> pull(problem)
  save_loc <- paste0(result_save_loc, "/", problem, ".rds")
  
  print(paste0("Comparing: ", problem))
  
  impostor_text <- read_jsonl_stream(paste0(impostors_loc, "/", known_author, ".jsonl")) |>
    select(corpus, author, texttype, rephrased) |>
    rename('text'='rephrased')
  
  known_text <- read_jsonl(known_loc) |>
    filter(author==known_author) |>
    mutate(doc_id = 'known') |>
    group_by(across(-text)) |>
    summarise(text = paste(text, collapse = " "), .groups = "drop")
  
  unknown_text <- read_jsonl(unknown_loc) |>
    filter(author==unknown_author) |>
    mutate(doc_id = author) |>
    group_by(across(-text)) |>
    summarise(text = paste(text, collapse = " "), .groups = "drop")
  
  known_corpus <- corpus(known_text)
  unknown_corpus <- corpus(unknown_text)
  impostor_corpus <- corpus(impostor_text)
  
  for(i in 1:nrow(impostor_text)){
    docvars(impostor_corpus)$author[i] <- paste0('impostor_', i)
  }
  
  # Do this only for LambdaG
  known_sents <- tokenize_sents(known_corpus)
  unknown_sents <- tokenize_sents(unknown_corpus)
  impostor_sents <- tokenize_sents(impostor_corpus)
  
  # Get the results
  final_result <- data.frame()
  
  for(i in 1:5){
    print(paste0("Repetition: ", i))
    # result <- impostors(unknown_corpus, known_corpus, impostor_corpus,
    #                     algorithm = "RBI", k = 100, features=FALSE, cores=7)
    result <- idiolect::lambdaG(unknown_sents, known_sents, impostor_sents)

    result_df <- cbind('repetition' = i, problem, known_author, unknown_author, result) |>
      select(repetition, problem, known_author, unknown_author, score)
    
    final_result <- rbind(final_result, result_df)
    
  }
  saveRDS(final_result, save_loc)
}

res <- idiolect::lambdaG_visualize(unknown_sents, known_sents, impostor_sents)
# install.packages("htmltools")   # if you don’t already have it
library(htmltools)

# your output is a character vector; collapse it into one big HTML fragment
html_frag <- paste0(res$colourcoded_text, collapse = "")

# send it to the Viewer (or browser) fully rendered
browsable( HTML(html_frag) )
# — or —
html_print( HTML(html_frag) )
# If i want to vectorize differently then use this but will need to then link for the top features
# vectorized_known <- vectorize(known_corpus, "character", remove_punct = T, remove_symbols = T,
#                               remove_numbers = T, lowercase = T, n = 4, weighting = 'rel', trim = F)
# vectorized_unknown <- vectorize(unknown_corpus, "character", remove_punct = T, remove_symbols = T,
#                               remove_numbers = T, lowercase = T, n = 4, weighting = 'rel', trim = F)
# vectorized_imp<- vectorize(impostor_corpus, "character", remove_punct = T, remove_symbols = T,
#                               remove_numbers = T, lowercase = T, n = 4, weighting = 'rel', trim = F)
# impostors(vectorized_unknown, vectorized_known, vectorized_imp, algorithm = "RBI", k = 300)