#--------------------------------------------------#
#-------------AUTHOR PROFILE IMPOSTORS-------------#
#--------------------------------------------------#

# This script runs the author profile version of the impostor method.
# This version differs from the traditional version of the method as it concatenates all known works by the author.
# The impostors are also generated by concatenating a random paraphrased document of each document number for each author.

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
})

source("/Users/user/Documents/GitHub/para_verifyr/rank_based_impostors_v2.R")

# Input variables
# selected_corpus since column called corpus in metadata
base_loc <- "/Volumes/BCross/datasets/author_verification"
data_type <- "training"
corpus <- "Enron"

# Locations
data_loc <- paste0(base_loc, "/", data_type, "/", corpus)

known_loc <- paste0(data_loc, "/known_profile_dfm.rds")
unknown_loc <- paste0(data_loc, "/unknown_raw_dfm.rds")
metadata_loc <-paste0(base_loc, "/", data_type, "/metadata.rds")
impostors_loc <- paste0(data_loc, "/gpt_4o_mini_full/impostor_profile_dfm")
features_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_feature_list.rds")
result_save_loc <- paste0(data_loc, "/gpt_4o_mini_full/profile_results")

if (!dir.exists(result_save_loc)) {
  dir.create(result_save_loc, recursive = TRUE)
}

# Get a list of all of the problems which have been completed.
# This is useful if an error occurs and you don't want to start over again.
completed_problems <- dir(result_save_loc, pattern = "\\.rds$")
completed_problems <- sub("\\.rds$", "", completed_problems)

# Read base files
known <- readRDS(known_loc)
unknown <- readRDS(unknown_loc)
metadata <- readRDS(metadata_loc)
feature_list <- readRDS(features_loc)

# Filter metadata for current corpus
filtered_metadata <- metadata |> 
  filter(corpus == .env$corpus) |>
  filter(!(problem %in% completed_problems)) |>
  rownames_to_column(var = 'sample_id')

# Get the sample_id vales
sample_ids <- filtered_metadata |> pull(sample_id)

for(s in sample_ids){
  
  chosen_sample <- filtered_metadata |>
    filter(sample_id == s)
  
  # Pull info for sample
  known_author <- chosen_sample |> pull(known_author)
  unknown_author <- chosen_sample |> pull(unknown_author)
  problem <- chosen_sample |> pull(problem)
  save_loc <- paste0(result_save_loc, "/", problem, ".rds")
  
  print(paste0("Comparing: ", problem))
  
  # Read the impostor dfm and filter the others
  impostor_dfm <- readRDS(paste0(impostors_loc, "/", known_author, "_dfm.rds"))
  known_dfm <- quanteda::dfm_subset(known, author == known_author)
  unknown_dfm <- quanteda::dfm_subset(unknown, author == unknown_author)
  
  final_result <- data.frame()
  
  for(i in 1:5){
  
    result <- rank_based_impostors_v2(known_dfm, unknown_dfm, impostor_dfm, feature_list, num_repetitions = 100)
    
    result_df <- cbind('repetition' = i, problem, known_author, unknown_author, result) |>
      select(repetition, problem, known_author, unknown_author, score)
    
    final_result <- rbind(final_result, result_df)
  }
  saveRDS(final_result, save_loc)
}