#--------------------------------------------------#
#------------AUTHOR INSTANCE IMPOSTORS-------------#
#--------------------------------------------------#

# This script runs the author profile version of the impostor method.
# This version differs from the traditional version of the method as it concatenates all known works by the author.
# The impostors are also generated by concatenating a random paraphrased document of each document number for each author.

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
})

source("/Users/user/Documents/GitHub/para_verifyr/rank_based_impostors_v2.R")

# Input variables
# selected_corpus since column called corpus in metadata
base_loc <- "/Volumes/BCross/datasets/author_verification"
data_type <- "training"
corpus <- "Wiki"

# Locations
data_loc <- paste0(base_loc, "/", data_type, "/", corpus)

known_loc <- paste0(data_loc, "/known_raw_dfm.rds")
unknown_loc <- paste0(data_loc, "/unknown_raw_dfm.rds")
metadata_loc <-paste0(base_loc, "/", data_type, "/metadata.rds")
impostors_loc <- paste0(data_loc, "/gpt_4o_mini_full/impostor_dfm")
features_loc <- paste0(data_loc, "/gpt_4o_mini_full/feature_list.rds")
result_save_loc <- paste0(data_loc, "/gpt_4o_mini_full/aggregated_results")

if (!dir.exists(result_save_loc)) {
  dir.create(result_save_loc, recursive = TRUE)
}

# Get a list of all of the problems which have been completed.
# This is useful if an error occurs and you don't want to start over again.
completed_problems <- dir(result_save_loc, pattern = "\\.rds$")
completed_problems <- sub("\\.rds$", "", completed_problems)

# Read base files
known <- readRDS(known_loc)
unknown <- readRDS(unknown_loc)
metadata <- readRDS(metadata_loc)
feature_list <- readRDS(features_loc)

# Add Doc ID to Known Docs
create_temp_doc_id <- function(input_text) {
  match <- regexec("\\[(.*?)\\]", input_text, perl = TRUE)
  match_result <- regmatches(input_text, match)
  
  if (length(match_result[[1]]) > 1) {
    extracted_text <- match_result[[1]][2]
    cleaned_text <- gsub("[^\\w]", "_", extracted_text, perl = TRUE)
    final_text <- gsub("_{2,}", "_", cleaned_text, perl = TRUE)
    return(tolower(final_text))
  }
  return(NULL)
}

docvars(known, "temp_id") <- sapply(docvars(known, "doc_id"), create_temp_doc_id)

# Remove any errors temporarily, if all files exist in top impostors leave vector blank
# Make sure to paste in as the file minus the .jsonl
error_texts <- c()
error_known_authors <- docvars(dfm_subset(known, temp_id %in% error_texts)) |> pull(author)

# Filter metadata for current corpus and remove any problems already complete.
filtered_metadata <- metadata |> 
  filter(corpus == .env$corpus) |>
  filter(!(problem %in% completed_problems)) |>
  filter(!(known_author %in% error_known_authors)) |>
  rownames_to_column(var = 'sample_id')

# Get the sample_id vales
sample_ids <- filtered_metadata |> pull(sample_id)
print(paste0("There are ", length(sample_ids), " docs left to process"))


# Perform The Impostor Method

for(s in sample_ids){
  
  chosen_sample <- filtered_metadata |>
    filter(sample_id == s)
  
  # Pull info for sample
  known_author <- chosen_sample |> pull(known_author)
  unknown_author <- chosen_sample |> pull(unknown_author)
  problem <- chosen_sample |> pull(problem)
  save_loc <- paste0(result_save_loc, "/", problem, ".rds")
  
  print(paste0("Comparing: ", problem))
  
  # Read the impostor dfm and filter the others
  author_known_dfm <- quanteda::dfm_subset(known, author == known_author)
  unknown_dfm <- quanteda::dfm_subset(unknown, author == unknown_author)
  
  # We want to pull the temp_id to loop through the documents
  known_docs <- docvars(author_known_dfm) |> pull(temp_id)

  # Create a dataframe to store Sample ID for all diff known docs
  final_result <- data.frame()
  
  # Loop across all known docs for each author
  for(kd in known_docs){
    
    # Filter the known dataframe for single doc and read the impostor
    known_dfm <- quanteda::dfm_subset(author_known_dfm, temp_id == kd)
    impostor_dfm <- readRDS(paste0(impostors_loc, "/", kd, "_dfm.rds"))
    
    # Perform the repetitions and bind the results
    for(i in 1:5){
      print(paste0("Repetition: ", i))
      result <- rank_based_impostors_v2(known_dfm, unknown_dfm, impostor_dfm, feature_list, num_repetitions = 100)
      
      result_df <- cbind('known_doc' = kd, 'repetition' = i, problem, known_author, unknown_author, result) |>
        select(known_doc, repetition, problem, known_author, unknown_author, score)
      
      final_result <- rbind(final_result, result_df)
    }
    saveRDS(final_result, save_loc)
  }
}

