#---------------------------------------------------------#
#--------------RUN ANDREAS AGGREGATED METHODS-------------#
#---------------------------------------------------------#

# This script runs the author profile version of the impostor method.
# This version differs from the traditional version of the method as it concatenates all known works by the author.
# The impostors are also generated by concatenating a random paraphrased document of each document number for each author.
suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(idiolect)
  library(jsonlite)
})

# Function to read a JSONL file into a data frame
read_jsonl <- function(file_path) {
  lines <- readLines(file_path)
  parsed_list <- lapply(lines, function(line) {
    parsed <- fromJSON(line)
    if (is.list(parsed) && length(parsed) == 1) {
      return(parsed[[1]])
    } else {
      return(parsed)
    }
  })
  df <- do.call(rbind, lapply(parsed_list, function(x) as.data.frame(x, stringsAsFactors = FALSE)))
  return(df)
}

# This method aids in reading list columns
read_jsonl_stream <- function(file_path) {
  con <- file(file_path, open = "r", encoding = "UTF-8")
  on.exit(close(con))
  
  # stream_in reads JSON objects line-by-line
  data <- jsonlite::stream_in(con, verbose = FALSE)
  return(data)
}

# Add Doc ID to Known Docs
create_temp_doc_id <- function(input_text) {
  match <- regexec("\\[(.*?)\\]", input_text, perl = TRUE)
  match_result <- regmatches(input_text, match)
  
  if (length(match_result[[1]]) > 1) {
    extracted_text <- match_result[[1]][2]
    cleaned_text <- gsub("[^\\w]", "_", extracted_text, perl = TRUE)
    final_text <- gsub("_{2,}", "_", cleaned_text, perl = TRUE)
    return(tolower(final_text))
  }
  return(NULL)
}


# Input variables
# selected_corpus since column called corpus in metadata
base_loc <- "/Volumes/BCross/datasets/author_verification"
data_type <- "training"
corpus <- "Wiki"

# Locations
data_loc <- paste0(base_loc, "/", data_type, "/", corpus)

known_loc <- paste0(data_loc, "/known_raw.jsonl")
unknown_loc <- paste0(data_loc, "/unknown_raw.jsonl")
metadata_loc <-paste0(base_loc, "/", data_type, "/metadata.rds")
impostors_loc <- paste0(data_loc, "/Qwen_2.5_1.5B/top_impostors")
# impostors_loc <- paste0(data_loc, "/gpt_4o_mini_full/impostor_profile_top_impostors")
# features_loc <- paste0(data_loc, "/gpt_4o_mini_full/feature_list.rds")
# LambdaG
result_save_loc <- paste0(data_loc, "/Qwen_2.5_1.5B/aggregated_results_lambdag")
# Impostors
result_save_loc <- paste0(data_loc, "/Qwen_2.5_1.5B/aggregated_results_impostors")

if (!dir.exists(result_save_loc)) {
  dir.create(result_save_loc, recursive = TRUE)
}

# Get a list of all of the problems which have been completed.
# This is useful if an error occurs and you don't want to start over again.
completed_problems <- dir(result_save_loc, pattern = "\\.rds$")
completed_problems <- sub("\\.rds$", "", completed_problems)

# Read base files
# known <- readRDS(known_loc)
# unknown <- readRDS(unknown_loc)
metadata <- readRDS(metadata_loc)
# feature_list <- readRDS(features_loc)

# Filter metadata for current corpus
filtered_metadata <- metadata |> 
  filter(corpus == .env$corpus) |>
  filter(!(problem %in% completed_problems)) |>
  rownames_to_column(var = 'sample_id') 

# Get the sample_id vales
sample_ids <- filtered_metadata |> pull(sample_id)

# Run the impostor method across samples
for(s in sample_ids){
  
  chosen_sample <- filtered_metadata |>
    filter(sample_id == s)
  
  known_author <- chosen_sample |> pull(known_author)
  unknown_author <- chosen_sample |> pull(unknown_author)
  problem <- chosen_sample |> pull(problem)
  save_loc <- paste0(result_save_loc, "/", problem, ".rds")
  
  print(paste0("Comparing: ", problem))
  
  known_text <- read_jsonl(known_loc) |>
    filter(author==known_author) |>
    mutate('temp_id' = sapply(doc_id, create_temp_doc_id))

  unknown_text <- read_jsonl(unknown_loc) |>
    filter(author==unknown_author) |>
    mutate('temp_id' = create_temp_doc_id(doc_id))
  
  known_corpus <- corpus(known_text)

  unknown_corpus <- corpus(unknown_text)
  
  # We want to pull the temp_id to loop through the documents
  known_docs <- docvars(known_corpus) |> pull(temp_id)

  # Get the results
  final_result <- data.frame()
  
  for(kd in known_docs){
    print(paste0("Known Document: ", kd))
    known_subset = quanteda::corpus_subset(known_corpus, temp_id == kd)

    impostor_file_path <- paste0(impostors_loc, "/", kd, ".jsonl")
    
    # Try both methods to read the file
    impostor_text <- tryCatch(
      read_jsonl(impostor_file_path),
      error = function(e) read_jsonl_stream(impostor_file_path)
    ) |>
      arrange(desc(parascore_free)) |>
      slice_head(n = 500) |>
      select(corpus, author, texttype, rephrased) |>
      rename(text = rephrased)

    impostor_corpus <- corpus(impostor_text)

    for(i in 1:nrow(impostor_text)){
      docvars(impostor_corpus)$author[i] <- paste0('impostor_', i)
    }
    
    # Do this only for LambdaG
    known_sents <- tokenize_sents(known_subset)
    unknown_sents <- tokenize_sents(unknown_corpus)
    impostor_sents <- tokenize_sents(impostor_corpus)

    for(i in 1:5){
      print(paste0("Repetition: ", i))
      result <- impostors(unknown_corpus, known_corpus, impostor_corpus,
                          algorithm = "RBI", k = 100, features=FALSE, cores=7)
      # result <- idiolect::lambdaG(unknown_sents, known_sents, impostor_sents)
      
      result_df <- cbind('known_doc' = kd, 'repetition' = i, problem, known_author, unknown_author, result) |>
        select(known_doc, repetition, problem, known_author, unknown_author, score)
      
      final_result <- rbind(final_result, result_df)
    }
  }
  saveRDS(final_result, save_loc)
}
